<?php

namespace App\Livewire\Admin;

use App\Enums\CustomerStatus;
use App\Models\Customer;
use App\Services\CustomerService;
use Livewire\Attributes\Layout;
use Livewire\Attributes\Title;
use Livewire\Attributes\Url;
use Livewire\Component;
use Livewire\WithPagination;

#[Layout('layouts.app')]
#[Title('العملاء')]
class CustomersIndex extends Component
{
    use WithPagination;

    #[Url]
    public string $search = '';

    /** Active filter: '' = all, '1' = active, '0' = inactive. */
    #[Url]
    public string $active = '';

    public bool $showForm = false;

    public ?int $editingId = null;

    // Simplified customer form — only three operational fields. The remaining
    // columns (contact_person, phone, city, address, tax_number, category,
    // source, status) stay in the database as legacy but are no longer edited
    // here. WhatsApp is the primary contact channel.
    public ?string $customer_number = null;

    public string $name = '';

    public string $whatsapp_number = '';

    public string $notes = '';

    public function mount(): void
    {
        $this->authorize('customers.view');
    }

    public function updating($name): void
    {
        if (in_array($name, ['search', 'active'], true)) {
            $this->resetPage();
        }
    }

    public function create(): void
    {
        $this->authorize('customers.create');
        $this->resetForm();
        $this->showForm = true;
    }

    public function edit(int $id): void
    {
        $this->authorize('customers.edit');
        $c = Customer::findOrFail($id);
        $this->editingId = $c->id;
        $this->customer_number = $c->customer_number;
        $this->name = $c->name;
        $this->whatsapp_number = (string) $c->whatsapp_number;
        $this->notes = (string) $c->notes;
        $this->showForm = true;
    }

    public function save(CustomerService $service): void
    {
        $this->authorize($this->editingId ? 'customers.edit' : 'customers.create');

        $validated = $this->validate([
            'name' => 'required|string|max:150',
            // Lenient rule: accepts local (0599432037) and international
            // (972599432037, +972 59 943 2037) Palestinian formats.
            'whatsapp_number' => ['required', 'string', 'max:40', 'regex:/^[0-9+()\-\s]{7,25}$/'],
            'notes' => 'nullable|string|max:2000',
        ], [], [
            'name' => 'الاسم',
            'whatsapp_number' => 'رقم واتساب',
            'notes' => 'ملاحظات',
        ]);

        $notes = ($validated['notes'] ?? '') !== '' ? $validated['notes'] : null;

        if ($this->editingId) {
            // Update only the three editable fields; legacy columns are untouched.
            $service->update(Customer::findOrFail($this->editingId), [
                'name' => $validated['name'],
                'whatsapp_number' => $validated['whatsapp_number'],
                'notes' => $notes,
            ]);
            session()->flash('status', 'تم تحديث العميل.');
        } else {
            // New customers are active by default; the internal number is
            // generated by the service. No status/lead selection at creation.
            $service->create([
                'name' => $validated['name'],
                'whatsapp_number' => $validated['whatsapp_number'],
                'notes' => $notes,
                'status' => CustomerStatus::Active->value,
                'is_active' => true,
            ]);
            session()->flash('status', 'تم إضافة العميل.');
        }

        $this->showForm = false;
        $this->resetForm();
    }

    public function archive(int $id, CustomerService $service): void
    {
        $this->authorize('customers.archive');
        $service->archive(Customer::findOrFail($id));
        session()->flash('status', 'تمت أرشفة العميل.');
    }

    private function resetForm(): void
    {
        $this->reset(['editingId', 'customer_number', 'name', 'whatsapp_number', 'notes']);
        $this->resetErrorBag();
    }

    public function render()
    {
        $customers = Customer::query()
            ->withCount('tasks')
            ->when($this->search !== '', fn ($q) => $q->where(fn ($q) => $q
                ->where('name', 'like', "%{$this->search}%")
                ->orWhere('customer_number', 'like', "%{$this->search}%")
                ->orWhere('whatsapp_number', 'like', "%{$this->search}%")))
            ->when($this->active !== '', fn ($q) => $q->where('is_active', $this->active === '1'))
            ->latest()
            ->paginate(15);

        $stats = [
            'total' => Customer::count(),
            'active' => Customer::where('is_active', true)->count(),
            'inactive' => Customer::where('is_active', false)->count(),
        ];

        return view('livewire.admin.customers-index', [
            'customers' => $customers,
            'stats' => $stats,
        ]);
    }
}
