<?php

namespace App\Enums;

/**
 * How a check-in/out timestamp was produced. Timestamps themselves are always
 * taken from the server clock; this records who/what triggered them.
 */
enum AttendanceSource: string
{
    case SelfService = 'self';       // employee tapped check-in/out
    case Adjustment = 'adjustment';  // an authorised user adjusted the record
    case System = 'system';          // generated by the system (e.g. leave sync)

    public function label(): string
    {
        return match ($this) {
            self::SelfService => 'ذاتي',
            self::Adjustment => 'تعديل إداري',
            self::System => 'النظام',
        };
    }
}
